#!/bin/sh
lb config noauto \
  --architecture amd64 \
  --distribution trixie \
  --archive-areas "main contrib non-free non-free-firmware" \
  --debian-installer live \
  --iso-volume "vimian" \
  "${@}"
